### ISSUE TITLE
`julia` not recognized in windows bash terminal

### ISSUE THREAD

**Issue by sbacelar** [johnnychen94/jill.py#103]
I have installed Julia 1.7.1 on Windows 10. Now when using the bash terminal I need to do `julia.cmd` (with the extension cmd) to run Julia.

This never happened to me before. It does not happen when I use PowerShell or cmd.

**Comment by johnnychen94** [comment]
> Now when using the bash terminal I need to do julia.cmd (with the extension cmd) to run Julia.

This might be due to be fact that `jill.py` creates "symlinks" as cmd file `julia.cmd` in `~\AppData\Local\julias\bin`, and bash terminal doesn't recognize it unless you type the full name.

**Comment by johnnychen94** [comment]
For bash terminal or julia shell that don't automatically translate "julia" to "julia.cmd". The symlinks are actually not working, and one has to manually add the `$INSTALL_DIR/bin` to PATH, e.g., `
C:\Users\jc\AppData\Local\julias\julia-1.7\bin`
