### ISSUE TITLE
Include `requirements.txt` in PyPI source

### ISSUE THREAD

**Issue by sugatoray** [johnnychen94/jill.py#110]
The `setup.py` file dynamically reads in from `requirements.txt`. But the source on PyPI does not include `requirements.txt`. Please add `requirements.txt` to the `MANIFEST.in` file -- this will add it to your source (`.tar.gz` file) on PyPI.

**Comment by sugatoray** [comment]
cc: @johnnychen94

**Comment by sugatoray** [comment]
I am working on adding `jill` to conda-forge channel to allow installation with conda.

- https://github.com/conda-forge/staged-recipes/pull/17624

**Comment by johnnychen94** [comment]
closed by #111
