### ISSUE TITLE
How to change the default installation directory used by jill.py?

### ISSUE THREAD

**Issue by hongyi-zhao** [johnnychen94/jill.py#113]
I'm on Ubuntu 20.04.3 LTS, and want to change the default installation directory `~/packages/julias` into `~/.julia`. How to achieve this aim?

BTW, when using [JILL](https://github.com/abelsiqueira/jill), this can be easily done as follows:

```shell
$ JULIA_DOWNLOAD=$HOME/.julia proxychains-ng-socks5 ./jill.sh 
```

Regards,
HZ

**Comment by johnnychen94** [comment]
Hi Hongyi, there are JILL_INSTALL_DIR and JILL_SYMLINK_DIR environment variables to specify this. You can check the README file for more details

**Comment by hongyi-zhao** [comment]
Thank you for your comments. The following methods can solve the problem:
```shell
$ pyenv shell datasci 
$ pip install -U jill
$ JILL_INSTALL_DIR=$HOME/.julia jill install 
```
