### ISSUE TITLE
Skip symlink generation

### ISSUE THREAD

**Issue by kerim371** [johnnychen94/jill.py#117]
Hi,

Is it possible to skip generation of symlink?
I can see an option `--symlink_dir` but it is a little unclear is it possible to use it to skip them?

**Comment by johnnychen94** [comment]
It's currently not allowed because I don't find this useful. Can you explain why you'd want to avoid using symlinks here?

**Comment by kerim371** [comment]
@johnnychen94 I'm trying to distribute julia along with my app. 
I use `jill` during C++ compilation and thus symbolic links point to the build folder (I don't need these links). 
As it doesn't affect users of my application this is not a big problem.
But if there were an option to skip symlink generation I would use it 😊

**Comment by johnnychen94** [comment]
That can be changed by adding a flag (maybe `--skip-symlinks`) and conditionally call all `make_symlinks` lines.

https://github.com/johnnychen94/jill.py/blob/8c751223051dc39213510ec5fe94fb30b0ae5c16/jill/install.py#L208

Would you want to submit a PR for it?

**Comment by kerim371** [comment]
@johnnychen94 
PR is ready #118 
Tested on Windows 11

**Comment by johnnychen94** [comment]
Thanks! I've tagged v0.11.1 for this.
