### ISSUE TITLE
jill fails with termux on android

### ISSUE THREAD

**Issue by ufechner7** [johnnychen94/jill.py#121]
I installed on android:
1. f-droid
2. termux
3. in termux I installed python
4. pip install jill
5. jill install 1.8

The last step fails with the signature verification.

Any idea?

**Comment by johnnychen94** [comment]
This is a rather weird use case to me, I'm afraid that I won't put any time into fixing it by myself. Sorry about this.

For signature verification, if you meant SSL verification, then you can pass `--bypass-ssl` flag, e.g., `jill install 1.8 --bypass-ssl`.

If you meant SHA256/MD5/GPG verification, then my best guess is that you have some network issue and get an incomplete download.
