### ISSUE TITLE
Can't swtich to `1.10`

### ISSUE THREAD

**Issue by wangl-cc** [johnnychen94/jill.py#123]
The version `1.10` was mistakenly parsed as `1.1`.
```bash
$ jill switch 1.10
Target /Users/loong/.local/bin/julia-1.1 doesn't exist.
False
```

**Comment by johnnychen94** [comment]
urghhh.. would you mind to submit a quick fix for this? I might not have the time to handle this until tomorrow night.

**Comment by wangl-cc** [comment]
After taking a quick look, it appears that fire treats version numbers like `1.10` as floats, which is also noted in the `switch_julia_target` function. To avoid this issue, would it be possible to accept version strings like `v1.10`?

**Comment by johnnychen94** [comment]
This could be `jill switch '"1.10"'` but I made a rather arbitrary choice here to parse both `jill switch 1.1` and `jill switch 1.10` to `jill switch '"1.10"'` as what we'd expect.

This said, Julia 1.1 is not supported by `jill switch` -- I believe nobody is going to use it anyway.

Julia 2.10 will be years away and I don't know if people still use jill then.
