### ISSUE TITLE
Integrate with diffeqpy

### ISSUE THREAD

**Issue by ChrisRackauckas** [johnnychen94/jill.py#50]
Is there a way to integrate this with https://github.com/SciML/diffeqpy to give users a function that sets up a Julia installation automatically? Right now we require users go out and install Julia, but it would be better if the package worked more like Conda.jl.

**Comment by johnnychen94** [comment]
I believe this is sufficient:

```python
from jill.install import install_julia

install_julia(confirm=True)
```

The log part isn't well written, so it doesn't support a quiet installation.

**Comment by ChrisRackauckas** [comment]
Is there a way to check if a Julia installation already exists?

**Comment by ChrisRackauckas** [comment]
Thanks, I think I got what I needed. Continuing the discussion in https://github.com/SciML/diffeqpy/pull/85
