### ISSUE TITLE
It would be nice to be able to use the current beta version in the same way as the nightlies

### ISSUE THREAD

**Issue by OvidiusCicero** [johnnychen94/jill.py#53]
It would be nice to be able to use the current beta version in the same way as the nightlies

**Comment by johnnychen94** [comment]
Do you mean `jill install 1.6.0-beta1`?

**Comment by OvidiusCicero** [comment]
yes…

**Comment by johnnychen94** [comment]
'jill install 1.6.0-beta1' this already works.

beta is not a fixed version name according to semantic versioning. A perhaps better usage is to make 'jill install 1 --include-rc' or so to include release candidate versions, but that requires some rewrite of jill's version resolver.

**Comment by OvidiusCicero** [comment]
works nice, thank you!

**Comment by johnnychen94** [comment]
Alright, I'll close this now.
