### ISSUE TITLE
Allow installation of release candidates

### ISSUE THREAD

**Issue by crstnbr** [johnnychen94/jill.py#54]
It doesn't seem to be possible to use `jill` to download the 1.6 release candidate:

```
➜  ~/.local/bin jill download 1.6
query the latest 1.6 version, it may take seconds...
version 1.6 is not available, use latest stable release.
```

Would be great if this were supported. Also, since we already have `jill install stable` and `jill install latest` we could also add something like `jill install beta` or `jill install rc` to install the latest rc candidate. 

(Note that an explicit `jill download 1.6.0-rc1` works. So it seems that `jill` is only checking for stable 1.6.x versions.)

**Comment by johnnychen94** [comment]
The current version query method does not support this in an easy way, so a possible way to support this is to query https://julialang-s3.julialang.org/bin/versions.json directly(as the time of writing jill.py, that wasn't available).

I'm not available recently to implement this, so if anyone wants to make a PR, I'll be very excited to help with that. As `jill install 1.6.0-rc1` already works, it's not an urgent issue, though.

**Comment by crstnbr** [comment]
I might give this a shot, but I can't promise anything (I'm also low on free time).

Rather than what I wrote in the OP, adding and `--unstable` option to `jill install` which will enable considering unstable releases sounds like the best idea to me.

**Comment by johnnychen94** [comment]
I'll see how things work with the new versions.json thing when `1.6.1` beta/rc versions are released.

**Comment by johnnychen94** [comment]
So now the case is that `jill install` automatically gives `1.7.0-beta1` by default. This is not wanted; these unstable versions should only be installed when users explicitly request them with `--unstable`.

```bash
➜ jill install
JILL - Julia Installer 4 Linux (MacOS, Windows and FreeBSD) -- Light

jill will:
  1) install Julia latest stable release for mac-x86_64 into /Applications
  2) make symlinks in /Users/jc/.local/bin
You may need to manually add /Users/jc/.local/bin to PATH
Continue installation? [Y/n]
querying release information from https://mirrors.ustc.edu.cn/julia-releases/bin/versions.json
----- Download Julia -----
downloading Julia release for 1.7.0-beta1-mac-x86_64
```
