### ISSUE TITLE
Improve printing output of `jill update`

### ISSUE THREAD

**Issue by crstnbr** [johnnychen94/jill.py#55]
Currently, you only get

```
➜  ~/repos/jill.py git:(master) jill update
check new Julia release info, it will take a while
```

Would be great if it would also tell the user whether it has found new versions and perhaps even what the latest stable version is.

**Comment by johnnychen94** [comment]
closed by #58

@crstnbr if you're going to close multiple issues/PRs, you have to duplicate the `close`, e.g.,

```
close #58
close #18
```
