### ISSUE TITLE
Why /Users/$HOME/.local/bin ?

### ISSUE THREAD

**Issue by Alalalalaki** [johnnychen94/jill.py#56]
I have some related questions about the installation of JILL.

First, why use `--user` in pip install? I haven't done this before. And I have to export `/Users/$HOME/.local/bin/` to PATH now. Is it common or unusual? Is it safe if I have some duplicated binaries in `/Users/$HOME/.local/bin/` and other paths? (I use conda env.)
 
Second, similarly jill install makes the symlinks to `/Users/$HOME/.local/bin` while the official document of Julia uses `/usr/local/bin/`. What's the difference of these two choices?

Third, 'jill install' add 3 symlinks, julia-1, julia-1.5, and julia to `/Users/$HOME/.local/bin`. They seems to link to the same Julia. So why do I need 3 versions? 

Thanks

**Comment by johnnychen94** [comment]
`pip install` with `--user` helps avoid permission issues by installing things in your home folder. The permission issue often occurs when `pip` is provided by `apt`/`yum` or other tools.

For `jill`, it's not `/Users/$HOME/.local/bin` but instead `$HOME/.local/bin`. Many terminal users to put their user-specific bin files to `$HOME/.local/bin` so as to again avoid the permission issue. Commonly you can take it as a user-owned version of `/usr/local/bin` which you need `root` privilege to modify this folder.

> They seems to link to the same Julia. So why do I need 3 versions?

Average users might only have one julia version at hand, in this case `julia` is all you need and you can ignore the other two safely. Julia package developers often switch from different julia versions to make sure their packages work for other versions, this is where this need arises. For example, I use both `julia` and `julia-latest` interchangeably and switch to specific minor version (e.g., `julia-1.3`) when people submit bug reports.

**Comment by Alalalalaki** [comment]
@johnnychen94  Thanks for the explanation.
