### ISSUE TITLE
Option to copy default environment to new Julia version

### ISSUE THREAD

**Issue by crstnbr** [johnnychen94/jill.py#59]
It might be nice to give the user the (command-line) option to automatically copy the Project.toml of the default environment, say, `~/.julia/environments/v1.5/Project.toml` to `~/.julia/environments/v1.6/` when updating (i.e. installing a newer version of) Julia.

**Comment by johnnychen94** [comment]
It's an experimental feature but you can use the `upgrade` flag.

```console
jill install --upgrade
```

https://github.com/johnnychen94/jill.py/blob/70a40d181841a05d426cfc7e04549221740f7502/jill/install.py#L255-L257
