### ISSUE TITLE
Possibility to set `--upstream` default

### ISSUE THREAD

**Issue by crstnbr** [johnnychen94/jill.py#60]
Currently, as per default, we are testing the latency to mirrors. While being a reasonable default, this leads to a somewhat annoying and unnecessary delay (e.g. I know that my connection to the official upstream is best, why test it all the time?).

I can avoid the latency test by providing `--upstream Official`. Would be great to have a way (a config?) to set a default upstream.

**Comment by crstnbr** [comment]
Default:

https://user-images.githubusercontent.com/187980/115028095-c886fb00-9ec4-11eb-88f7-a3e328e46f60.mp4

`--upstream Official`:
https://user-images.githubusercontent.com/187980/115028115-cc1a8200-9ec4-11eb-8931-f6158403eb3c.mp4

**Comment by johnnychen94** [comment]
> Would be great to have a way (a config?) to set a default upstream.

Maybe an environment variable `JILL_UPSTREAM`?
