### ISSUE TITLE
Windows下make_symlinks不正确

### ISSUE THREAD

**Issue by yemeng77** [johnnychen94/jill.py#65]
非常感谢这一程序方便了安装Julia。但今天发现0.9.1版本在Windows下创建symlinks调用的是mklink导致报错。检查是在make_symlinks()中110、139、168行处应由“windows”改为“winnt”，修改后可以正常安装。应该是修改了current_system()的返回值后没有完全修改对应的位置，不知道还有没有需要修改的。

**Comment by johnnychen94** [comment]
0.9的改动比较大，因为我这里没有windows 系统所以没有完全覆盖到测试. 方便的话可以提交一个 PR 么？

**Comment by yemeng77** [comment]
OK. 我又发现了几处需要修改的，已提交pr

**Comment by johnnychen94** [comment]
我晚一点会发布一个新版本
