### ISSUE TITLE
`choco` in readme?

### ISSUE THREAD

**Issue by zmoon** [johnnychen94/jill.py#69]
>  Distro package managers (e.g., apt, pac, chocho) is likely to provide a broken Julia with incorrect binary dependencies (e.g., LLVM ) versions. Hence it's recommended to download and extract the Julia binary provided in Julia Downloads.

I believe `chocho` should be `choco`?

Also, assuming `choco` was meant, to be fair to Chocolatey, [it does](https://community.chocolatey.org/packages/Julia#files) just use the official Julia `.exe` binary download. The MD5 checksum is the same. So in that sense alone I would not think that `jill.py` provides any benefit over installing Julia with `choco`. IMHO the benefit is that with `jill.py` you can easily have multiple Julia versions accessible.

**Comment by johnnychen94** [comment]
Ah, correct... I didn't realize that choco uses official `.exe`. Sorry for the misleading and thanks for the note.
