### ISSUE TITLE
Env variable for installation dir

### ISSUE THREAD

**Issue by crstnbr** [johnnychen94/jill.py#79]
Apart from the `--install_dir` cmd option it would be nice to be able to specify a fixed installation directory via an environment variable, e.g. `JILL_INSTALL_DIR`.

**Comment by johnnychen94** [comment]
LGTM, PR's welcome. And maybe also to `JILL_SYMLINK_DIR`.

**Comment by johnnychen94** [comment]
ah never mind, I'll make a PR later
