### ISSUE TITLE
Does not work on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by thomarse-ef** [johnnychen94/jill.py#85]
Getting this error:
```
pi@raspberrypi:~ $ jill install 1.6.2
JILL - Julia Installer 4 Linux (MacOS, Windows and FreeBSD) -- Light

jill will:
  1) install Julia 1.6.2 for linux-armv6l into /home/pi/packages/julias
  2) make symlinks in /home/pi/.local/bin
You may need to manually add /home/pi/.local/bin to PATH
Continue installation? [Y/n] y
----- Download Julia -----
downloading Julia release for 1.6.2-linux-armv6l
failed to find 1.6.2-linux-armv6l in available upstreams. Please try it later.
False
```
Presumably because there is no `armv6l` version in https://julialang-s3.julialang.org/bin/versions.json

How to fix this?

**Comment by johnnychen94** [comment]
Maybe try `1.6.1` or other versions instead.

This versions.json file needs upstream to manually update, so keep patient!

I've submitted a MacOS PR there https://github.com/SaschaMann/Julia-versions.json/pull/8 so hopefully, there'll be updated soon.

**Comment by thomarse-ef** [comment]
I tried searching `armv6l` in https://julialang-s3.julialang.org/bin/versions.json - not found! Hopefully it will be updated soon.

**Comment by johnnychen94** [comment]
Wait. armv6l?

**Comment by thomarse-ef** [comment]
Yep

**Comment by johnnychen94** [comment]
There's no armv6l binary release... You will have to compile from source code...

**Comment by johnnychen94** [comment]
Okay... This is clearly not a jill.py issue, because jill.py only downloads the prebuilt official binary releases. I don't think Julia will ship armv6l binaries in the future.

**Comment by thomarse-ef** [comment]
OK, thanks
