### ISSUE TITLE
I can't find the julia installation path under pycharm after installing with jill?

### ISSUE THREAD

**Issue by banduoba** [johnnychen94/jill.py#86]
What is the installation path of julia?
![image](https://user-images.githubusercontent.com/4811366/127758300-5e88afa5-22fb-496d-b21d-9fb90236ef30.png)

**Comment by johnnychen94** [comment]
I don't know how to configure pycharm, but you can use something like `which julia | xargs ls -l` to get it. For example, in my machine it is:

```julia
$ which julia | xargs ls -l
lrwxr-xr-x  1 jc  staff  62 Jul 14 13:27 /Users/jc/.local/bin/julia -> /Applications/Julia-1.7.app/Contents/Resources/julia/bin/julia
```
