### ISSUE TITLE
jill list bug

### ISSUE THREAD

**Issue by carstenbauer** [johnnychen94/jill.py#94]
<img width="1145" alt="Screenshot 2021-08-28 at 14 15 03" src="https://user-images.githubusercontent.com/187980/131217540-691d0dff-35a0-4cd2-ae43-a16c91ae7a48.png">

**Comment by johnnychen94** [comment]
Oh damn! It is a direct commit https://github.com/johnnychen94/jill.py/commit/ec61a134a593a38d8ff1c99aa9652a851d09cb85 that mess this up.

**Comment by johnnychen94** [comment]
fixed by another direct commit a91b5e7523aabb3988c38fd1e2deed57cbe42c54 :)
