### ISSUE TITLE
 How to uninstall the specified version of Julia?

### ISSUE THREAD

**Issue by OUCyf** [johnnychen94/jill.py#96]
Hi~
I use jill in my MacBook and I want to know how to uninstall the specified version of Julia? By manual manipulation or something else?

Thanks

Fu

**Comment by johnnychen94** [comment]
To completely uninstall julia installed by jill on macOS:

* delete the julia folder in `install_dir`, e.g., `/Applications/Julia-1.6.app`
* optionally remove the symlinks in `symlink_dir`, e.g., `~/.local/bin/julia-1.6`

So for instance, run the following codes if you want to remove Julia-1.6:

```console
rm -rf /Applications/Julia-1.6.app
rm ~/.local/bin/julia-1.6
# maybe also
rm ~/.local/bin/julia-1
rm ~/.local/bin/julia
```

**Comment by OUCyf** [comment]
Thanks~
The path `~/.julia` also have some Julia files, whether to remove?

**Comment by johnnychen94** [comment]
`~/.julia` is used to store Julia packages, precompiled files, environments and etc. If you meant to uninstall Julia and don't plan to use Julia anymore, then yes, you can also remove that folder.

**Comment by OUCyf** [comment]
Yep, I know that. 
- For example, I use `jill` to install 2 versions eg. Julia-1.5 and Julia-1.6, and I use both of them. Duing to some reasons, I need to uninstall the julia-1.5 and all the packages of it, and don't break environment of Julia-1.6. 
- I found some all packages will be stored in `~/.julia`; so how to distinguish those packages between different versions of Julia.

**Comment by johnnychen94** [comment]
> Duing to some reasons, I need to uninstall the julia-1.5 and all the packages of it, and don't break environment of Julia-1.6.

The following codes should be sufficient:

```bash
rm -rf /Applications/Julia-1.5.app
rm ~/.local/bin/julia-1.5
```

>  I found some all packages will be stored in ~/.julia; so how to distinguish those packages between different versions of Julia.

All Julia packages are installed in `~/.julia/packages/` in version-agnostic manner; whether a specific package version is used depends on the environment you're using. For instance, `~/.julia/environments/v1.6/Manifest.toml` specifies all julia package versions. There isn't `~/.julia/packages/v1.6` stuff. Thus you don't need to worry about this at all.

If you want to cleanup some spaces, you can try `pkg> gc` in Pkg mode. Or if you insist, another way is to manually remove `~/.julia/packages` folder and then `pkg> instantiate` to rebuild it.

**Comment by OUCyf** [comment]
Oh! I got the point. Thanks so much!

With best wishes~

**Comment by xsa-dev** [comment]
Thanks!
